# Generated by Django 6.0.6 on 2026-06-05 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='meal_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='meal_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
