# Generated by Django 6.0.6 on 2026-06-05 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('category', models.CharField(choices=[('rent', 'Rent / Lease'), ('utilities', 'Utilities'), ('equipment', 'Equipment'), ('office_supplies', 'Office Supplies'), ('marketing', 'Marketing & Advertising'), ('maintenance', 'Maintenance & Repairs'), ('other', 'Other')], default='other', max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expense_date', models.DateField()),
                ('receipt_file', models.FileField(blank=True, null=True, upload_to='expense_receipts/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_expenses', to='hr.employee')),
            ],
            options={
                'ordering': ['-expense_date'],
            },
        ),
        migrations.CreateModel(
            name='ProfitLossSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('daily', 'Daily'), ('monthly', 'Monthly')], max_length=10)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_material_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_labor_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_operating_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('gross_profit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('net_profit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('units_sold', models.PositiveIntegerField(default=0)),
                ('generated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-period_start'],
                'unique_together': {('period_type', 'period_start')},
            },
        ),
    ]
