# Generated by Django 6.0.6 on 2026-06-05 01:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIQueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField(help_text='The natural language question the user asked')),
                ('db_context_snapshot', models.TextField(blank=True, help_text='The database summary injected into the Gemini prompt at query time')),
                ('response', models.TextField(help_text='The raw text response returned by Gemini')),
                ('prompt_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('response_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('latency_ms', models.PositiveIntegerField(blank=True, help_text='Round-trip time in milliseconds', null=True)),
                ('was_successful', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_queries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Query Log',
                'verbose_name_plural': 'AI Query Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
